version: "3"

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:11.13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis:6.2.5-alpine
    command: redis-server --requirepass redis-pass
    ports:
      - "6379:6379"

  fullapp:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    image: fullapp:latest
    entrypoint: /fullapp/docker-compose-entrypoint.sh
    command: ['rails', 'server', '-b', '0.0.0.0', '-p', '5011']
    ports:
      - 5011:5011
    volumes:
      - ./:/fullapp
    stdin_open: true
    tty: true
    environment:
      - "RAILS_LOG_TO_STDOUT=true"
      - "RAILS_ENV=development"
      - "APP_URL_HOST=http://0.0.0.0:5011"
    depends_on:
      - redis
      - postgres