version: "1"

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis:6.2.5-alpine
    command: redis-server --requirepass redis-pass
    ports:
      - "6379:6379"

  fullapp:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    image: fullapp:latest
    entrypoint: /fullapp/docker-compose-entrypoint.sh
    command: bash -c "foreman start -f Procfile.dev"
    ports:
      - 3000:3000
    volumes:
      - ./:/fullapp
    stdin_open: true
    tty: true
    environment:
      - "RAILS_LOG_TO_STDOUT=true"
      - "RAILS_ENV=development"
      - "APP_URL_HOST=http://0.0.0.0:3000"
    depends_on:
      - redis
      - postgres
